<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 --types --transform 3D-Moon-NASA-textures-v1.1.glb
-->

<script lang="ts">
  import type * as THREE from "three";

  import type { Snippet } from "svelte";
  import { T, type Props } from "@threlte/core";
  import { useGltf, useDraco } from "@threlte/extras";

  import gltfPath from "./3D-Moon-NASA-textures-v1.1-transformed.glb?url";

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    position = [0, -40, 0],
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group;
    children?: Snippet<[{ ref: THREE.Group }]>;
    fallback?: Snippet;
    error?: Snippet<[{ error: Error }]>;
    position?: [number, number, number];
  } = $props();

  type GLTFResult = {
    nodes: {
      Moon: THREE.Mesh;
    };
    materials: {
      ["Material.001"]: THREE.MeshStandardMaterial;
    };
  };

  const gltf = useGltf<GLTFResult>(gltfPath, {
    dracoLoader: useDraco(),
  });
</script>

<T.Group bind:ref dispose={false} {...props} {position}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.Moon.geometry}
      material={gltf.materials["Material.001"]}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {#if ref}}
    {@render children?.({ ref })}
  {/if}
</T.Group>
