<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 --types --transform NASA_SLS-block-1-v2.glb
-->

<script lang="ts">
  import * as THREE from "three";

  import type { Snippet } from "svelte";
  import { T, type Props } from "@threlte/core";
  import { useGltf, useDraco } from "@threlte/extras";

  const dracoLoader = useDraco();

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group;
    children?: Snippet<[{ ref: THREE.Group }]>;
    fallback?: Snippet;
    error?: Snippet<[{ error: Error }]>;
  } = $props();

  type GLTFResult = {
    nodes: {
      core: THREE.Mesh;
      ["srb-left"]: THREE.Mesh;
      ["core-left-fill"]: THREE.Mesh;
      ["srb-right"]: THREE.Mesh;
      ["core-right-fill"]: THREE.Mesh;
      las: THREE.Mesh;
      csm: THREE.Mesh;
      icps: THREE.Mesh;
      lvsa: THREE.Mesh;
      ["rs-25"]: THREE.Mesh;
    };
    materials: object;
  };

  import gltfPath from "./NASA_SLS-block-1-v2-transformed.glb?url";

  const gltf = useGltf<GLTFResult>(gltfPath, { dracoLoader });

  const standardMaterial = new THREE.MeshStandardMaterial({
    roughness: 0.7,
    metalness: 0.1,
    opacity: 0.5,
    transparent: true,
    depthWrite: false,
  });
</script>

<T.Group bind:ref dispose={false} {...props}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.core.geometry}
      material={standardMaterial}
    ></T.Mesh>
    <T.Mesh
      geometry={gltf.nodes["srb-left"].geometry}
      material={standardMaterial}
    ></T.Mesh>
    <T.Mesh
      geometry={gltf.nodes["core-left-fill"].geometry}
      material={standardMaterial}
    />
    <T.Mesh
      geometry={gltf.nodes["srb-right"].geometry}
      material={standardMaterial}
    />
    <T.Mesh
      geometry={gltf.nodes["core-right-fill"].geometry}
      material={standardMaterial}
    />
    <T.Mesh geometry={gltf.nodes.las.geometry} material={standardMaterial} />
    <T.Mesh geometry={gltf.nodes.csm.geometry} material={standardMaterial} />
    <T.Mesh geometry={gltf.nodes.icps.geometry} material={standardMaterial} />
    <T.Mesh geometry={gltf.nodes.lvsa.geometry} material={standardMaterial} />
    <T.Mesh
      geometry={gltf.nodes["rs-25"].geometry}
      material={standardMaterial}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {#if ref}
    {@render children?.({ ref })}
  {/if}
</T.Group>
