<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 --types --transform 3D-Moon-NASA-textures-v1.1.glb
-->

<script lang="ts">
  import * as THREE from "three";

  import type { Snippet } from "svelte";
  import { T, type Props, useTask } from "@threlte/core";
  import { useGltf, useDraco } from "@threlte/extras";

  import gltfPath from "./3D-Moon-NASA-textures-v1.1_compressed.glb?url";

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group;
    children?: Snippet<[{ ref: THREE.Group }]>;
    fallback?: Snippet;
    error?: Snippet<[{ error: Error }]>;
  } = $props();

  type GLTFResult = {
    nodes: {
      Moon: THREE.Mesh;
    };
    materials: {
      ["Material.001"]: THREE.MeshStandardMaterial;
    };
  };

  const gltf = useGltf<GLTFResult>(gltfPath, {
    dracoLoader: useDraco(),
  });
</script>

<T.Group bind:ref dispose={false} {...props}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.Moon.geometry}
      material={gltf.materials["Material.001"]}
      oncreate={(ref) => {
        const mat = ref.material as THREE.MeshStandardMaterial;

        const heightMap = mat.normalMap; // grab it before nulling
        mat.normalMap = null;
        mat.bumpMap = heightMap;
        mat.bumpScale = 0.4;
        mat.needsUpdate = true;

        
      }}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {#if ref}
    {@render children?.({ ref })}
  {/if}
</T.Group>
