<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 --types Orion_Draco_Optimized.glb
-->

<script lang="ts">
  import type * as THREE from "three";

  import type { Snippet } from "svelte";
  import { T, type Props, useThrelte } from "@threlte/core";
  import { useGltf, useDraco } from "@threlte/extras";
  const { invalidate } = useThrelte();

  const ROUGHNESS = 0.7;
  const METALNESS = 0.1;

  const dracoLoader = useDraco();

  import gltfPath from "./Orion_Draco_Optimized.glb?url";

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    opacity = 1,
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group;
    children?: Snippet<[{ ref: THREE.Group }]>;
    fallback?: Snippet;
    error?: Snippet<[{ error: Error }]>;
    opacity?: number;
  } = $props();

  type GLTFResult = {
    nodes: {
      Orion_Plug: THREE.Mesh;
      Orion_Nofbc: THREE.Mesh;
      Capsule_Stand: THREE.Mesh;
    };
    materials: {
      Material: THREE.MeshStandardMaterial;
      ["Material.004"]: THREE.MeshStandardMaterial;
    };
  };

  const gltf = useGltf<GLTFResult>(gltfPath, { dracoLoader });

  let isTransparent = $derived(opacity < 1);
</script>

<T.Group bind:ref dispose={false} {...props}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    {#if !isTransparent}
      <T.Mesh
        geometry={gltf.nodes.Orion_Plug.geometry}
        position={[0, 0.13, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.38}
      >
        <T.MeshStandardMaterial
          roughness={ROUGHNESS}
          metalness={METALNESS}
          {opacity}
          transparent={isTransparent}
          depthWrite={!isTransparent}
        />
      </T.Mesh>
      <T.Mesh
        geometry={gltf.nodes.Orion_Nofbc.geometry}
        position={[0, 0.72, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={2.15}
      >
        <T.MeshStandardMaterial
          roughness={ROUGHNESS}
          metalness={METALNESS}
          {opacity}
          transparent={isTransparent}
          depthWrite={!isTransparent}
        />
      </T.Mesh>
      <T.Mesh
        geometry={gltf.nodes.Capsule_Stand.geometry}
        position={[0.68, -0.45, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.45}
      >
        <T.MeshStandardMaterial
          roughness={ROUGHNESS}
          metalness={METALNESS}
          {opacity}
          transparent={isTransparent}
          depthWrite={!isTransparent}
        />
      </T.Mesh>
    {/if}
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {#if ref}
    {@render children?.({ ref })}
  {/if}
</T.Group>
