<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 --types --transform cornish-pasty-v1.8.glb
-->

<script lang="ts">
  import type * as THREE from "three";

  import type { Snippet } from "svelte";
  import { T, type Props } from "@threlte/core";
  import { useGltf, useDraco } from "@threlte/extras";

  const dracoLoader = useDraco();

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group;
    children?: Snippet<[{ ref: THREE.Group }]>;
    fallback?: Snippet;
    error?: Snippet<[{ error: Error }]>;
  } = $props();

  type GLTFResult = {
    nodes: {
      ["cornish-pasty_1"]: THREE.Mesh;
      ["cornish-pasty_2"]: THREE.Mesh;
      ["weather-ballon001"]: THREE.Mesh;
      ["weather-ballon001_1"]: THREE.Mesh;
      tray001: THREE.Mesh;
      tray001_1: THREE.Mesh;
    };
    materials: {
      ["cornish-pasty-wireframe"]: THREE.MeshStandardMaterial;
      ["cornish-pasty-wireframe-fill"]: THREE.MeshStandardMaterial;
    };
  };

  import gltfPath from "./cornish-pasty-v1.8-transformed.glb?url";
  const gltf = useGltf<GLTFResult>(gltfPath, { dracoLoader });
</script>

<T.Group bind:ref dispose={false} {...props}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group
      position={[0, 0.12, 0]}
      rotation={[0, 1.57, -1.57]}
      scale={[-0.8, -0.51, -1]}
    >
      <T.Mesh
        geometry={gltf.nodes["cornish-pasty_1"].geometry}
        material={gltf.materials["cornish-pasty-wireframe"]}
      />
      <T.Mesh
        geometry={gltf.nodes["cornish-pasty_2"].geometry}
        material={gltf.materials["cornish-pasty-wireframe-fill"]}
      />
    </T.Group>
    <T.Group position={[0, 4.82, 0]}>
      <T.Mesh
        geometry={gltf.nodes["weather-ballon001"].geometry}
        material={gltf.materials["cornish-pasty-wireframe"]}
      />
      <T.Mesh
        geometry={gltf.nodes["weather-ballon001_1"].geometry}
        material={gltf.materials["cornish-pasty-wireframe-fill"]}
      />
    </T.Group>
    <T.Group position={[0, -0.04, 0]} scale={[1.14, 0.06, 1]}>
      <T.Mesh
        geometry={gltf.nodes.tray001.geometry}
        material={gltf.materials["cornish-pasty-wireframe"]}
      />
      <T.Mesh
        geometry={gltf.nodes.tray001_1.geometry}
        material={gltf.materials["cornish-pasty-wireframe-fill"]}
      />
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {#if ref}
    {@render children?.({ ref })}
  {/if}
</T.Group>
