<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 --types ISS_stationary.glb
-->

<script lang="ts">
  import type * as THREE from 'three'

  import type { Snippet } from 'svelte'
  import { T, type Props } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group
    children?: Snippet<[{ ref: THREE.Group }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  type GLTFResult = {
    nodes: {
      Cylinder022_7: THREE.Mesh
      Cylinder022_8: THREE.Mesh
      Cylinder022_9: THREE.Mesh
      Cylinder022_10: THREE.Mesh
      Cylinder022_11: THREE.Mesh
      Cylinder022_12: THREE.Mesh
      Cylinder022_13: THREE.Mesh
      Sphere002: THREE.Mesh
      Sphere002_1: THREE.Mesh
      Sphere002_2: THREE.Mesh
      Sphere002_3: THREE.Mesh
      sm_ext_sm000: THREE.Mesh
      sm_ext_sm000_1: THREE.Mesh
      sm_ext_sm000_2: THREE.Mesh
      sm_ext_sm000_3: THREE.Mesh
      sm_ext_sm000_4: THREE.Mesh
      Sphere002_8: THREE.Mesh
      Sphere002_9: THREE.Mesh
      Sphere002_10: THREE.Mesh
      Sphere002_11: THREE.Mesh
      Sphere002_12: THREE.Mesh
      Sphere002_13: THREE.Mesh
      Sphere002_14: THREE.Mesh
      Sphere002_15: THREE.Mesh
      sm_ext_sm000_5: THREE.Mesh
      sm_ext_sm000_6: THREE.Mesh
      sm_ext_sm000_7: THREE.Mesh
      sm_ext_sm000_8: THREE.Mesh
      sm_ext_sm000_9: THREE.Mesh
      sm_ext_sm000_10: THREE.Mesh
      sm_ext_sm000_11: THREE.Mesh
      sm_ext_sm000_12: THREE.Mesh
      sm_ext_sm000_13: THREE.Mesh
      sm_ext_sm000_14: THREE.Mesh
      sm_ext_sm000_15: THREE.Mesh
      sm_ext_sm000_16: THREE.Mesh
      sm_ext_sm000_17: THREE.Mesh
      sm_ext_sm000_18: THREE.Mesh
      sm_ext_sm000_19: THREE.Mesh
      sm_ext_sm000_20: THREE.Mesh
      sm_ext_sm000_21: THREE.Mesh
      sm_ext_sm000_22: THREE.Mesh
      sm_ext_sm000_23: THREE.Mesh
      sm_ext_sm000_24: THREE.Mesh
      sm_ext_sm000_25: THREE.Mesh
      sm_ext_sm000_26: THREE.Mesh
      sm_ext_sm000_27: THREE.Mesh
      sm_ext_sm000_28: THREE.Mesh
      sm_ext_sm000_29: THREE.Mesh
      sm_ext_sm000_30: THREE.Mesh
      sm_ext_sm000_31: THREE.Mesh
      sm_ext_sm000_32: THREE.Mesh
      sm_ext_sm000_33: THREE.Mesh
      sm_ext_sm000_34: THREE.Mesh
      sm_ext_sm000_35: THREE.Mesh
      sm_ext_sm000_36: THREE.Mesh
      sm_ext_sm000_37: THREE.Mesh
      sm_ext_sm000_38: THREE.Mesh
      sm_ext_sm000_39: THREE.Mesh
      sm_ext_sm000_40: THREE.Mesh
      sm_ext_sm000_41: THREE.Mesh
      sm_ext_sm000_42: THREE.Mesh
      sm_ext_sm000_43: THREE.Mesh
      sm_ext_sm000_44: THREE.Mesh
      sm_ext_sm000_45: THREE.Mesh
      sm_ext_sm000_46: THREE.Mesh
      sm_ext_sm000_47: THREE.Mesh
      sm_ext_sm000_48: THREE.Mesh
      sm_ext_sm000_49: THREE.Mesh
      sm_ext_sm000_50: THREE.Mesh
      sm_ext_sm000_51: THREE.Mesh
      sm_ext_sm000_52: THREE.Mesh
      sm_ext_sm000_53: THREE.Mesh
      sm_ext_sm000_54: THREE.Mesh
      sm_ext_sm000_55: THREE.Mesh
      sm_ext_sm000_56: THREE.Mesh
      sm_ext_sm000_57: THREE.Mesh
      sm_ext_sm000_58: THREE.Mesh
      panel_bracket_p: THREE.Mesh
      panel_bracket_s: THREE.Mesh
      Sphere002_4: THREE.Mesh
      Sphere002_5: THREE.Mesh
      Sphere002_6: THREE.Mesh
      Sphere002_7: THREE.Mesh
      z1_ext_01001: THREE.Mesh
      z1_ext_01001_1: THREE.Mesh
      z1_ext_01001_2: THREE.Mesh
      z1_ext_01001_3: THREE.Mesh
      z1_ext_01001_4: THREE.Mesh
      Cylinder022_14: THREE.Mesh
      Cylinder022_15: THREE.Mesh
      Cylinder022_16: THREE.Mesh
      Cylinder022_17: THREE.Mesh
      Cylinder022_18: THREE.Mesh
      Cylinder022_19: THREE.Mesh
      z1_ext_01001_5: THREE.Mesh
      z1_ext_01001_6: THREE.Mesh
      s0_ani000: THREE.Mesh
      s0_ani000_1: THREE.Mesh
      s0_ani000_2: THREE.Mesh
      s0_ani000_3: THREE.Mesh
      s0_ani000_4: THREE.Mesh
      mss_mbs001: THREE.Mesh
      mss_mbs001_1: THREE.Mesh
      mss_mbs001_2: THREE.Mesh
      mss_mbs001_3: THREE.Mesh
      ['11_Canadarm2']: THREE.Mesh
      ['11_Canadarm2_02']: THREE.Mesh
      ['11_Canadarm2_03']: THREE.Mesh
      ['11_Canadarm2_04']: THREE.Mesh
      ['11_Canadarm2_05']: THREE.Mesh
      ['11_Canadarm2_06']: THREE.Mesh
      ['11_Canadarm2_07']: THREE.Mesh
      ['11_Canadarm2_08']: THREE.Mesh
      Cylinder022_83: THREE.Mesh
      Cylinder022_84: THREE.Mesh
      ['29_DEXTRE001']: THREE.Mesh
      ['29_DEXTRE002']: THREE.Mesh
      ['29_DEXTRE003']: THREE.Mesh
      ['29_DEXTRE004']: THREE.Mesh
      ['29_DEXTRE005']: THREE.Mesh
      ['29_DEXTRE006']: THREE.Mesh
      ['29_DEXTRE007']: THREE.Mesh
      ['29_DEXTRE008']: THREE.Mesh
      ['29_DEXTRE009']: THREE.Mesh
      ['29_DEXTRE010']: THREE.Mesh
      ['29_DEXTRE011']: THREE.Mesh
      ['29_DEXTRE012']: THREE.Mesh
      ['29_DEXTRE013']: THREE.Mesh
      ['29_DEXTRE014']: THREE.Mesh
      ['29_DEXTRE015']: THREE.Mesh
      s0_ani000_5: THREE.Mesh
      s0_ani000_6: THREE.Mesh
      s0_ani000_7: THREE.Mesh
      s0_ani000_8: THREE.Mesh
      s0_ani000_9: THREE.Mesh
      s0_ani000_15: THREE.Mesh
      s0_ani000_16: THREE.Mesh
      s0_ani000_17: THREE.Mesh
      s0_ani000_18: THREE.Mesh
      s0_ani000_19: THREE.Mesh
      s0_ani000_20: THREE.Mesh
      s0_ani000_21: THREE.Mesh
      p6_ani000: THREE.Mesh
      p6_ani000_1: THREE.Mesh
      p6_ani000_2: THREE.Mesh
      p6_ani000_3: THREE.Mesh
      p6_ani000_4: THREE.Mesh
      Cube008_46: THREE.Mesh
      Cube008_47: THREE.Mesh
      Cube008_48: THREE.Mesh
      Cube008_49: THREE.Mesh
      p6_ani000_10: THREE.Mesh
      p6_ani000_11: THREE.Mesh
      p6_ani000_12: THREE.Mesh
      p6_ani000_13: THREE.Mesh
      p6_ani000_14: THREE.Mesh
      p6_ani000_15: THREE.Mesh
      p6_ani000_16: THREE.Mesh
      p6_ani000_17: THREE.Mesh
      p6_ani000_18: THREE.Mesh
      p6_ani000_19: THREE.Mesh
      p6_ani000_30: THREE.Mesh
      p6_ani000_31: THREE.Mesh
      p6_ani000_32: THREE.Mesh
      p6_ani000_33: THREE.Mesh
      p6_ani000_34: THREE.Mesh
      p6_ani000_35: THREE.Mesh
      ESP3000: THREE.Mesh
      ESP3000_1: THREE.Mesh
      ESP3000_2: THREE.Mesh
      ESP3000_3: THREE.Mesh
      ESP3000_4: THREE.Mesh
      esp2_lo000_4: THREE.Mesh
      esp2_lo000_5: THREE.Mesh
      esp2_lo000_6: THREE.Mesh
      esp2_lo000_7: THREE.Mesh
      esp2_lo000_8: THREE.Mesh
      esp2_lo000_9: THREE.Mesh
      esp2_lo000_10: THREE.Mesh
      AMS2000: THREE.Mesh
      AMS2000_1: THREE.Mesh
      AMS2000_2: THREE.Mesh
      Cylinder022_63: THREE.Mesh
      Cylinder022_64: THREE.Mesh
      Cylinder022_65: THREE.Mesh
      s0_ani000_10: THREE.Mesh
      s0_ani000_11: THREE.Mesh
      s0_ani000_12: THREE.Mesh
      s0_ani000_13: THREE.Mesh
      s0_ani000_14: THREE.Mesh
      s0_ani000_22: THREE.Mesh
      s0_ani000_23: THREE.Mesh
      s0_ani000_24: THREE.Mesh
      s0_ani000_25: THREE.Mesh
      s0_ani000_26: THREE.Mesh
      s0_ani000_27: THREE.Mesh
      s0_ani000_28: THREE.Mesh
      p6_ani000_5: THREE.Mesh
      p6_ani000_6: THREE.Mesh
      p6_ani000_7: THREE.Mesh
      p6_ani000_8: THREE.Mesh
      p6_ani000_9: THREE.Mesh
      Cube008_50: THREE.Mesh
      Cube008_51: THREE.Mesh
      Cube008_52: THREE.Mesh
      Cube008_53: THREE.Mesh
      p6_ani000_20: THREE.Mesh
      p6_ani000_21: THREE.Mesh
      p6_ani000_22: THREE.Mesh
      p6_ani000_23: THREE.Mesh
      p6_ani000_36: THREE.Mesh
      p6_ani000_37: THREE.Mesh
      p6_ani000_38: THREE.Mesh
      p6_ani000_39: THREE.Mesh
      p6_ani000_40: THREE.Mesh
      p6_ani000_41: THREE.Mesh
      p6_ani000_24: THREE.Mesh
      p6_ani000_25: THREE.Mesh
      p6_ani000_26: THREE.Mesh
      p6_ani000_27: THREE.Mesh
      p6_ani000_28: THREE.Mesh
      p6_ani000_29: THREE.Mesh
      esp2_lo000_11: THREE.Mesh
      esp2_lo000_12: THREE.Mesh
      esp2_lo000_13: THREE.Mesh
      esp2_lo000_14: THREE.Mesh
      esp2_lo000_15: THREE.Mesh
      esp2_lo000_16: THREE.Mesh
      esp2_lo000_17: THREE.Mesh
      esp2_lo000_18: THREE.Mesh
      Cylinder022_36: THREE.Mesh
      Cylinder022_37: THREE.Mesh
      Cylinder022_38: THREE.Mesh
      Cylinder022_39: THREE.Mesh
      Cylinder022_46: THREE.Mesh
      Cylinder022_47: THREE.Mesh
      Cylinder022_48: THREE.Mesh
      Cylinder022_49: THREE.Mesh
      Cylinder022_50: THREE.Mesh
      Cylinder022_51: THREE.Mesh
      Cylinder022_52: THREE.Mesh
      Cylinder022_53: THREE.Mesh
      Cylinder022_54: THREE.Mesh
      Cube008_35: THREE.Mesh
      Cube008_36: THREE.Mesh
      Cube008_37: THREE.Mesh
      Cube008_38: THREE.Mesh
      RapidScat_dish: THREE.Mesh
      Cylinder022_55: THREE.Mesh
      Cylinder022_56: THREE.Mesh
      Cylinder022_57: THREE.Mesh
      Cylinder022_58: THREE.Mesh
      Cylinder022_59: THREE.Mesh
      Cylinder022_60: THREE.Mesh
      Cylinder022_66: THREE.Mesh
      Cylinder022_67: THREE.Mesh
      Cylinder022_68: THREE.Mesh
      Cylinder022_69: THREE.Mesh
      Cylinder022_70: THREE.Mesh
      Cylinder022_71: THREE.Mesh
      ['31_Robotic_Arm']: THREE.Mesh
      ['31_Robotic_Arm001']: THREE.Mesh
      ['31_Robotic_Arm002']: THREE.Mesh
      ['31_Robotic_Arm003']: THREE.Mesh
      ['31_Robotic_Arm004']: THREE.Mesh
      ['31_Robotic_Arm005']: THREE.Mesh
      Cube008_39: THREE.Mesh
      Cube008_40: THREE.Mesh
      Cube008_41: THREE.Mesh
      Cube008_42: THREE.Mesh
      Cube008_43: THREE.Mesh
      Cube008_44: THREE.Mesh
      Destiny_Window_Cover: THREE.Mesh
      Cylinder022_20: THREE.Mesh
      Cylinder022_21: THREE.Mesh
      Cylinder022_22: THREE.Mesh
      Cylinder022_23: THREE.Mesh
      Cylinder022_24: THREE.Mesh
      Cylinder022_25: THREE.Mesh
      Cylinder022_26: THREE.Mesh
      esp2_lo000: THREE.Mesh
      esp2_lo000_1: THREE.Mesh
      esp2_lo000_2: THREE.Mesh
      esp2_lo000_3: THREE.Mesh
      Cylinder022_27: THREE.Mesh
      Cylinder022_28: THREE.Mesh
      Cylinder022_29: THREE.Mesh
      Cylinder022_30: THREE.Mesh
      Cylinder022_40: THREE.Mesh
      Cylinder022_41: THREE.Mesh
      Cylinder022_42: THREE.Mesh
      Cylinder022_43: THREE.Mesh
      Cylinder022_44: THREE.Mesh
      Cylinder022_45: THREE.Mesh
      ['38_Cupola001']: THREE.Mesh
      ['38_Cupola002']: THREE.Mesh
      ['38_Cupola003']: THREE.Mesh
      ['38_Cupola004']: THREE.Mesh
      ['38_Cupola005']: THREE.Mesh
      ['38_Cupola006']: THREE.Mesh
      ['38_Cupola007']: THREE.Mesh
      ISS: THREE.Mesh
      Cylinder022_31: THREE.Mesh
      Cylinder022_32: THREE.Mesh
      Cylinder022_33: THREE.Mesh
      Cylinder022_34: THREE.Mesh
      Cylinder022_35: THREE.Mesh
      Cube008: THREE.Mesh
      Cube008_1: THREE.Mesh
      hinge_02_p: THREE.Mesh
      Cube008_3: THREE.Mesh
      Cube008_4: THREE.Mesh
      hinge_04_p: THREE.Mesh
      hinge_01_p: THREE.Mesh
      Cube008_7: THREE.Mesh
      Cube008_8: THREE.Mesh
      hinge_03_p: THREE.Mesh
      Cube008_10: THREE.Mesh
      Cube008_11: THREE.Mesh
      Cube008_12: THREE.Mesh
      Cube008_13: THREE.Mesh
      hinge_02_s: THREE.Mesh
      Cube008_15: THREE.Mesh
      Cube008_16: THREE.Mesh
      hinge_04_s: THREE.Mesh
      hinge_03_s: THREE.Mesh
      Cube008_19: THREE.Mesh
      Cube008_20: THREE.Mesh
      Cube008_21: THREE.Mesh
      Cube008_22: THREE.Mesh
      hinge_01_s: THREE.Mesh
      Cube008_24: THREE.Mesh
      Cube008_25: THREE.Mesh
      Cube008_26: THREE.Mesh
      Cube008_27: THREE.Mesh
      Cylinder022: THREE.Mesh
      Cylinder022_1: THREE.Mesh
      Cylinder022_2: THREE.Mesh
      Cylinder022_3: THREE.Mesh
      Cylinder022_4: THREE.Mesh
      Cylinder022_5: THREE.Mesh
      Cylinder022_6: THREE.Mesh
    }
    materials: {
      ISS_01_dull: THREE.MeshStandardMaterial
      ISS_01_shiny_n: THREE.MeshStandardMaterial
      ISS_AO_01: THREE.MeshStandardMaterial
      ISS_AO_02: THREE.MeshStandardMaterial
      ISS_02_dull: THREE.MeshStandardMaterial
      ISS_03_dull: THREE.MeshStandardMaterial
      ISS_AO_06: THREE.MeshStandardMaterial
      shiny_panel: THREE.MeshStandardMaterial
      ['olive *']: THREE.MeshStandardMaterial
      ISS_AO_04: THREE.MeshStandardMaterial
      ISS_AO_03: THREE.MeshStandardMaterial
      ['ISS_01_dark *']: THREE.MeshStandardMaterial
      foil_silver: THREE.MeshStandardMaterial
      ISS_03_shiny_n: THREE.MeshStandardMaterial
      ['ISS_02_dark *']: THREE.MeshStandardMaterial
      ISS_04_dull: THREE.MeshStandardMaterial
      ISS_AO_05: THREE.MeshStandardMaterial
      ISS_AO_07: THREE.MeshStandardMaterial
      ISS_AO_08: THREE.MeshStandardMaterial
      white: THREE.MeshStandardMaterial
      base_metal: THREE.MeshStandardMaterial
      ['ISS_03_dull.001']: THREE.MeshStandardMaterial
      ecostress: THREE.MeshStandardMaterial
      ['plastic black']: THREE.MeshStandardMaterial
      ecostressWhite: THREE.MeshStandardMaterial
      ['ISS_03_dull.002']: THREE.MeshStandardMaterial
      ['ecostress metal']: THREE.MeshStandardMaterial
      ecostress_dexter: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/ISS_stationary.glb')
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group position={[1.69, 0.85, -11.09]}>
      <T.Mesh
        geometry={gltf.nodes.Cube008.geometry}
        material={gltf.materials.ISS_02_dull}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube008_1.geometry}
        material={gltf.materials.shiny_panel}
      />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.hinge_02_p.geometry}
      material={gltf.materials.ISS_02_dull}
      position={[2.17, 0.8, -12.51]}
    />
    <T.Group position={[2.94, 0.8, -9.63]}>
      <T.Mesh
        geometry={gltf.nodes.Cube008_3.geometry}
        material={gltf.materials.ISS_02_dull}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube008_4.geometry}
        material={gltf.materials.shiny_panel}
      />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.hinge_04_p.geometry}
      material={gltf.materials.ISS_02_dull}
      position={[3.91, 0.8, -12.5]}
    />
    <T.Mesh
      geometry={gltf.nodes.hinge_01_p.geometry}
      material={gltf.materials.ISS_02_dull}
      position={[1.69, 0.8, -11.09]}
    />
    <T.Group position={[2.17, 0.8, -9.66]}>
      <T.Mesh
        geometry={gltf.nodes.Cube008_7.geometry}
        material={gltf.materials.ISS_02_dull}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube008_8.geometry}
        material={gltf.materials.shiny_panel}
      />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.hinge_03_p.geometry}
      material={gltf.materials.ISS_02_dull}
      position={[2.93, 0.8, -12.54]}
    />
    <T.Group position={[3.91, 0.8, -9.68]}>
      <T.Mesh
        geometry={gltf.nodes.Cube008_10.geometry}
        material={gltf.materials.ISS_02_dull}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube008_11.geometry}
        material={gltf.materials.shiny_panel}
      />
    </T.Group>
    <T.Group position={[-1.69, 0.85, -11.09]}>
      <T.Mesh
        geometry={gltf.nodes.Cube008_12.geometry}
        material={gltf.materials.ISS_02_dull}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube008_13.geometry}
        material={gltf.materials.shiny_panel}
      />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.hinge_02_s.geometry}
      material={gltf.materials.ISS_02_dull}
      position={[-2.17, 0.8, -12.51]}
    />
    <T.Group position={[-2.94, 0.8, -9.63]}>
      <T.Mesh
        geometry={gltf.nodes.Cube008_15.geometry}
        material={gltf.materials.shiny_panel}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube008_16.geometry}
        material={gltf.materials.ISS_02_dull}
      />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.hinge_04_s.geometry}
      material={gltf.materials.ISS_02_dull}
      position={[-3.91, 0.8, -12.5]}
    />
    <T.Mesh
      geometry={gltf.nodes.hinge_03_s.geometry}
      material={gltf.materials.ISS_02_dull}
      position={[-2.93, 0.8, -12.54]}
    />
    <T.Group position={[-3.91, 0.8, -9.68]}>
      <T.Mesh
        geometry={gltf.nodes.Cube008_19.geometry}
        material={gltf.materials.shiny_panel}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube008_20.geometry}
        material={gltf.materials.ISS_02_dull}
      />
    </T.Group>
    <T.Group position={[-2.17, 0.8, -9.66]}>
      <T.Mesh
        geometry={gltf.nodes.Cube008_21.geometry}
        material={gltf.materials.shiny_panel}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube008_22.geometry}
        material={gltf.materials.ISS_02_dull}
      />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.hinge_01_s.geometry}
      material={gltf.materials.ISS_02_dull}
      position={[-1.69, 0.8, -11.09]}
    />
    <T.Group position={[15.53, -2.12, 19.9]}>
      <T.Mesh
        geometry={gltf.nodes.Cube008_24.geometry}
        material={gltf.materials.white}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube008_25.geometry}
        material={gltf.materials.base_metal}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube008_26.geometry}
        material={gltf.materials.ISS_01_dull}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube008_27.geometry}
        material={gltf.materials['ISS_03_dull.001']}
      />
    </T.Group>
    <T.Group position={[18.91, -1.96, 16.11]}>
      <T.Mesh
        geometry={gltf.nodes.Cylinder022.geometry}
        material={gltf.materials.ecostress}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder022_1.geometry}
        material={gltf.materials['plastic black']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder022_2.geometry}
        material={gltf.materials.ecostressWhite}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder022_3.geometry}
        material={gltf.materials['ISS_03_dull.002']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder022_4.geometry}
        material={gltf.materials['ecostress metal']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder022_5.geometry}
        material={gltf.materials.ISS_01_dull}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder022_6.geometry}
        material={gltf.materials.ecostress_dexter}
      />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.Cylinder022_7.geometry}
      material={gltf.nodes.Cylinder022_7.material}
    />
    <T.Mesh
      geometry={gltf.nodes.Cylinder022_8.geometry}
      material={gltf.materials.ISS_01_dull}
    />
    <T.Mesh
      geometry={gltf.nodes.Cylinder022_9.geometry}
      material={gltf.materials.ISS_01_shiny_n}
    />
    <T.Mesh
      geometry={gltf.nodes.Cylinder022_10.geometry}
      material={gltf.materials.ISS_AO_01}
    />
    <T.Group position={[0, 0, -3.38]}>
      <T.Mesh
        geometry={gltf.nodes.Cylinder022_11.geometry}
        material={gltf.materials.ISS_AO_02}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder022_12.geometry}
        material={gltf.materials.ISS_AO_01}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder022_13.geometry}
        material={gltf.materials.ISS_01_dull}
      />
      <T.Group position={[0, 0.73, -2.46]}>
        <T.Mesh
          geometry={gltf.nodes.Sphere002.geometry}
          material={gltf.nodes.Sphere002.material}
        />
        <T.Mesh
          geometry={gltf.nodes.Sphere002_1.geometry}
          material={gltf.materials.ISS_02_dull}
        />
        <T.Mesh
          geometry={gltf.nodes.Sphere002_2.geometry}
          material={gltf.materials.ISS_01_dull}
        />
        <T.Mesh
          geometry={gltf.nodes.Sphere002_3.geometry}
          material={gltf.materials.ISS_AO_02}
        />
        <T.Group position={[0, 0, -12.96]}>
          <T.Mesh
            geometry={gltf.nodes.sm_ext_sm000.geometry}
            material={gltf.nodes.sm_ext_sm000.material}
          />
          <T.Mesh
            geometry={gltf.nodes.sm_ext_sm000_1.geometry}
            material={gltf.materials.ISS_03_dull}
          />
          <T.Mesh
            geometry={gltf.nodes.sm_ext_sm000_2.geometry}
            material={gltf.materials.ISS_02_dull}
          />
          <T.Mesh
            geometry={gltf.nodes.sm_ext_sm000_3.geometry}
            material={gltf.materials.ISS_01_dull}
          />
          <T.Mesh
            geometry={gltf.nodes.sm_ext_sm000_4.geometry}
            material={gltf.materials.ISS_AO_02}
          />
          <T.Group position={[0, -1.16, -1.16]}>
            <T.Mesh
              geometry={gltf.nodes.Sphere002_8.geometry}
              material={gltf.materials.ISS_03_dull}
            />
            <T.Mesh
              geometry={gltf.nodes.Sphere002_9.geometry}
              material={gltf.materials.ISS_AO_06}
            />
            <T.Mesh
              geometry={gltf.nodes.Sphere002_10.geometry}
              material={gltf.materials.ISS_01_dull}
            />
            <T.Mesh
              geometry={gltf.nodes.Sphere002_11.geometry}
              material={gltf.materials.ISS_02_dull}
            />
          </T.Group>
          <T.Group position={[0, 1.16, -1.16]}>
            <T.Mesh
              geometry={gltf.nodes.Sphere002_12.geometry}
              material={gltf.materials.ISS_03_dull}
            />
            <T.Mesh
              geometry={gltf.nodes.Sphere002_13.geometry}
              material={gltf.materials.ISS_AO_06}
            />
            <T.Mesh
              geometry={gltf.nodes.Sphere002_14.geometry}
              material={gltf.materials.ISS_01_dull}
            />
            <T.Mesh
              geometry={gltf.nodes.Sphere002_15.geometry}
              material={gltf.materials.ISS_02_dull}
            />
          </T.Group>
          <T.Group position={[2.23, -0.03, -5.26]}>
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_5.geometry}
              material={gltf.materials.shiny_panel}
            />
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_6.geometry}
              material={gltf.materials.ISS_02_dull}
            />
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_7.geometry}
              material={gltf.materials['olive *']}
            />
          </T.Group>
          <T.Group position={[-2.23, -0.03, -5.26]}>
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_8.geometry}
              material={gltf.materials.shiny_panel}
            />
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_9.geometry}
              material={gltf.materials.ISS_02_dull}
            />
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_10.geometry}
              material={gltf.materials['olive *']}
            />
          </T.Group>
          <T.Group position={[3.51, -0.03, -5.26]}>
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_11.geometry}
              material={gltf.materials.shiny_panel}
            />
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_12.geometry}
              material={gltf.materials.ISS_02_dull}
            />
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_13.geometry}
              material={gltf.materials['olive *']}
            />
          </T.Group>
          <T.Group position={[-3.51, -0.03, -5.26]}>
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_14.geometry}
              material={gltf.materials.shiny_panel}
            />
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_15.geometry}
              material={gltf.materials.ISS_02_dull}
            />
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_16.geometry}
              material={gltf.materials['olive *']}
            />
          </T.Group>
          <T.Group position={[5.03, -0.03, -5.26]}>
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_17.geometry}
              material={gltf.materials.shiny_panel}
            />
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_18.geometry}
              material={gltf.materials.ISS_02_dull}
            />
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_19.geometry}
              material={gltf.materials['olive *']}
            />
          </T.Group>
          <T.Group position={[-5.03, -0.03, -5.26]}>
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_20.geometry}
              material={gltf.materials.shiny_panel}
            />
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_21.geometry}
              material={gltf.materials.ISS_02_dull}
            />
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_22.geometry}
              material={gltf.materials['olive *']}
            />
          </T.Group>
          <T.Group position={[6.56, -0.03, -5.26]}>
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_23.geometry}
              material={gltf.materials.shiny_panel}
            />
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_24.geometry}
              material={gltf.materials.ISS_02_dull}
            />
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_25.geometry}
              material={gltf.materials['olive *']}
            />
          </T.Group>
          <T.Group position={[-6.56, -0.03, -5.26]}>
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_26.geometry}
              material={gltf.materials.shiny_panel}
            />
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_27.geometry}
              material={gltf.materials.ISS_02_dull}
            />
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_28.geometry}
              material={gltf.materials['olive *']}
            />
          </T.Group>
          <T.Group position={[8.07, -0.03, -5.26]}>
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_29.geometry}
              material={gltf.materials.shiny_panel}
            />
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_30.geometry}
              material={gltf.materials.ISS_02_dull}
            />
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_31.geometry}
              material={gltf.materials['olive *']}
            />
          </T.Group>
          <T.Group position={[-8.07, -0.03, -5.26]}>
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_32.geometry}
              material={gltf.materials.shiny_panel}
            />
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_33.geometry}
              material={gltf.materials.ISS_02_dull}
            />
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_34.geometry}
              material={gltf.materials['olive *']}
            />
          </T.Group>
          <T.Group position={[9.58, -0.03, -5.26]}>
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_35.geometry}
              material={gltf.materials.shiny_panel}
            />
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_36.geometry}
              material={gltf.materials.ISS_02_dull}
            />
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_37.geometry}
              material={gltf.materials['olive *']}
            />
          </T.Group>
          <T.Group position={[-9.58, -0.03, -5.26]}>
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_38.geometry}
              material={gltf.materials.shiny_panel}
            />
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_39.geometry}
              material={gltf.materials.ISS_02_dull}
            />
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_40.geometry}
              material={gltf.materials['olive *']}
            />
          </T.Group>
          <T.Group position={[11.16, -0.03, -5.26]}>
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_41.geometry}
              material={gltf.materials.ISS_02_dull}
            />
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_42.geometry}
              material={gltf.materials.shiny_panel}
            />
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_43.geometry}
              material={gltf.materials['olive *']}
            />
          </T.Group>
          <T.Group position={[-11.16, -0.03, -5.26]}>
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_44.geometry}
              material={gltf.materials.ISS_02_dull}
            />
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_45.geometry}
              material={gltf.materials.shiny_panel}
            />
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_46.geometry}
              material={gltf.materials['olive *']}
            />
          </T.Group>
          <T.Group position={[12.74, -0.03, -5.26]}>
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_47.geometry}
              material={gltf.materials.shiny_panel}
            />
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_48.geometry}
              material={gltf.materials.ISS_02_dull}
            />
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_49.geometry}
              material={gltf.materials['olive *']}
            />
          </T.Group>
          <T.Group position={[-12.74, -0.03, -5.26]}>
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_50.geometry}
              material={gltf.materials.shiny_panel}
            />
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_51.geometry}
              material={gltf.materials.ISS_02_dull}
            />
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_52.geometry}
              material={gltf.materials['olive *']}
            />
          </T.Group>
          <T.Group position={[14.33, -0.03, -5.26]}>
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_53.geometry}
              material={gltf.materials.shiny_panel}
            />
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_54.geometry}
              material={gltf.materials.ISS_02_dull}
            />
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_55.geometry}
              material={gltf.materials['olive *']}
            />
          </T.Group>
          <T.Group position={[-14.33, -0.03, -5.26]}>
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_56.geometry}
              material={gltf.materials.shiny_panel}
            />
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_57.geometry}
              material={gltf.materials.ISS_02_dull}
            />
            <T.Mesh
              geometry={gltf.nodes.sm_ext_sm000_58.geometry}
              material={gltf.materials['olive *']}
            />
          </T.Group>
          <T.Mesh
            geometry={gltf.nodes.panel_bracket_p.geometry}
            material={gltf.materials['olive *']}
            position={[1.9, -0.03, -5.26]}
          />
          <T.Mesh
            geometry={gltf.nodes.panel_bracket_s.geometry}
            material={gltf.materials['olive *']}
            position={[-1.9, -0.03, -5.26]}
          />
        </T.Group>
        <T.Group position={[0, -4.59, -1.15]}>
          <T.Mesh
            geometry={gltf.nodes.Sphere002_4.geometry}
            material={gltf.materials.ISS_01_dull}
          />
          <T.Mesh
            geometry={gltf.nodes.Sphere002_5.geometry}
            material={gltf.materials.ISS_03_dull}
          />
          <T.Mesh
            geometry={gltf.nodes.Sphere002_6.geometry}
            material={gltf.materials.ISS_02_dull}
          />
          <T.Mesh
            geometry={gltf.nodes.Sphere002_7.geometry}
            material={gltf.materials.ISS_AO_04}
          />
        </T.Group>
      </T.Group>
    </T.Group>
    <T.Group position={[0, 1.76, 0]}>
      <T.Mesh
        geometry={gltf.nodes.z1_ext_01001.geometry}
        material={gltf.materials.ISS_01_dull}
      />
      <T.Mesh
        geometry={gltf.nodes.z1_ext_01001_1.geometry}
        material={gltf.materials.ISS_AO_03}
      />
      <T.Mesh
        geometry={gltf.nodes.z1_ext_01001_2.geometry}
        material={gltf.materials.ISS_01_shiny_n}
      />
      <T.Mesh
        geometry={gltf.nodes.z1_ext_01001_3.geometry}
        material={gltf.materials['ISS_01_dark *']}
      />
      <T.Mesh
        geometry={gltf.nodes.z1_ext_01001_4.geometry}
        material={gltf.materials.foil_silver}
      />
    </T.Group>
    <T.Group position={[0, 0, 2.22]}>
      <T.Mesh
        geometry={gltf.nodes.Cylinder022_14.geometry}
        material={gltf.nodes.Cylinder022_14.material}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder022_15.geometry}
        material={gltf.materials.ISS_AO_03}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder022_16.geometry}
        material={gltf.materials.ISS_01_dull}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder022_17.geometry}
        material={gltf.materials.ISS_AO_01}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder022_18.geometry}
        material={gltf.materials.ISS_01_shiny_n}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder022_19.geometry}
        material={gltf.materials.ISS_03_shiny_n}
      />
      <T.Group position={[2.73, -0.48, 2.01]}>
        <T.Mesh
          geometry={gltf.nodes.z1_ext_01001_5.geometry}
          material={gltf.materials.ISS_01_dull}
        />
        <T.Mesh
          geometry={gltf.nodes.z1_ext_01001_6.geometry}
          material={gltf.materials.ISS_03_dull}
        />
      </T.Group>
      <T.Group position={[0, 5.01, 0.97]}>
        <T.Mesh
          geometry={gltf.nodes.s0_ani000.geometry}
          material={gltf.materials.ISS_02_dull}
        />
        <T.Mesh
          geometry={gltf.nodes.s0_ani000_1.geometry}
          material={gltf.materials['ISS_02_dark *']}
        />
        <T.Mesh
          geometry={gltf.nodes.s0_ani000_2.geometry}
          material={gltf.materials.ISS_01_dull}
        />
        <T.Mesh
          geometry={gltf.nodes.s0_ani000_3.geometry}
          material={gltf.materials.ISS_AO_04}
        />
        <T.Mesh
          geometry={gltf.nodes.s0_ani000_4.geometry}
          material={gltf.materials.ISS_04_dull}
        />
        <T.Group position={[-2.87, -0.6, 5.17]}>
          <T.Mesh
            geometry={gltf.nodes.mss_mbs001.geometry}
            material={gltf.materials.ISS_02_dull}
          />
          <T.Mesh
            geometry={gltf.nodes.mss_mbs001_1.geometry}
            material={gltf.materials.ISS_01_dull}
          />
          <T.Mesh
            geometry={gltf.nodes.mss_mbs001_2.geometry}
            material={gltf.materials.ISS_AO_05}
          />
          <T.Mesh
            geometry={gltf.nodes.mss_mbs001_3.geometry}
            material={gltf.materials.ISS_03_dull}
          />
          <T.Mesh
            geometry={gltf.nodes['11_Canadarm2'].geometry}
            material={gltf.materials.ISS_03_dull}
            position={[-1.43, 1.59, 0.2]}
          >
            <T.Mesh
              geometry={gltf.nodes['11_Canadarm2_02'].geometry}
              material={gltf.materials.ISS_03_dull}
              position={[-0.67, 0.36, 0.98]}
            >
              <T.Mesh
                geometry={gltf.nodes['11_Canadarm2_03'].geometry}
                material={gltf.materials.ISS_03_dull}
                position={[-0.01, 0.36, 0.23]}
              >
                <T.Mesh
                  geometry={gltf.nodes['11_Canadarm2_04'].geometry}
                  material={gltf.materials.ISS_03_dull}
                  position={[0.13, 0.25, 0.31]}
                >
                  <T.Mesh
                    geometry={gltf.nodes['11_Canadarm2_05'].geometry}
                    material={gltf.materials.ISS_03_dull}
                    position={[-7.34, 0, 0.58]}
                  >
                    <T.Mesh
                      geometry={gltf.nodes['11_Canadarm2_06'].geometry}
                      material={gltf.materials.ISS_03_dull}
                      position={[0, 7.34, 0.58]}
                    >
                      <T.Mesh
                        geometry={gltf.nodes['11_Canadarm2_07'].geometry}
                        material={gltf.materials.ISS_03_dull}
                        position={[-0.29, 0, 0.31]}
                      >
                        <T.Mesh
                          geometry={gltf.nodes['11_Canadarm2_08'].geometry}
                          material={gltf.materials.ISS_03_dull}
                          position={[-0.31, 0.29, 0]}
                        >
                          <T.Group position={[0, 1.2, 0]}>
                            <T.Mesh
                              geometry={gltf.nodes.Cylinder022_83.geometry}
                              material={gltf.materials.ISS_03_dull}
                            />
                            <T.Mesh
                              geometry={gltf.nodes.Cylinder022_84.geometry}
                              material={gltf.materials.ISS_01_dull}
                            />
                            <T.Mesh
                              geometry={gltf.nodes['29_DEXTRE001'].geometry}
                              material={gltf.materials.ISS_03_dull}
                              position={[0, 0.22, 0]}
                            >
                              <T.Mesh
                                geometry={gltf.nodes['29_DEXTRE002'].geometry}
                                material={gltf.materials.ISS_03_dull}
                                position={[0, 1.96, 0.01]}
                              >
                                <T.Mesh
                                  geometry={gltf.nodes['29_DEXTRE003'].geometry}
                                  material={gltf.materials.ISS_03_dull}
                                  position={[0, 0.96, 0]}
                                />
                              </T.Mesh>
                              <T.Mesh
                                geometry={gltf.nodes['29_DEXTRE004'].geometry}
                                material={gltf.materials.ISS_03_dull}
                                position={[1.38, 1.43, 0]}
                              >
                                <T.Mesh
                                  geometry={gltf.nodes['29_DEXTRE005'].geometry}
                                  material={gltf.materials.ISS_03_dull}
                                  position={[0.37, -0.1, 0.27]}
                                >
                                  <T.Mesh
                                    geometry={gltf.nodes['29_DEXTRE006'].geometry}
                                    material={gltf.materials.ISS_03_dull}
                                    position={[0.3, -0.11, 0.14]}
                                  >
                                    <T.Mesh
                                      geometry={gltf.nodes['29_DEXTRE007'].geometry}
                                      material={gltf.materials.ISS_03_dull}
                                      position={[1.09, 0.01, 0.06]}
                                    >
                                      <T.Mesh
                                        geometry={gltf.nodes['29_DEXTRE008'].geometry}
                                        material={gltf.materials.ISS_03_dull}
                                        position={[1.09, -0.01, -0.33]}
                                      >
                                        <T.Mesh
                                          geometry={gltf.nodes['29_DEXTRE009'].geometry}
                                          material={gltf.materials.ISS_03_dull}
                                          position={[0.28, -0.12, -0.11]}
                                        />
                                      </T.Mesh>
                                    </T.Mesh>
                                  </T.Mesh>
                                </T.Mesh>
                              </T.Mesh>
                              <T.Mesh
                                geometry={gltf.nodes['29_DEXTRE010'].geometry}
                                material={gltf.materials.ISS_03_dull}
                                position={[-1.38, 1.43, 0]}
                              >
                                <T.Mesh
                                  geometry={gltf.nodes['29_DEXTRE011'].geometry}
                                  material={gltf.materials.ISS_03_dull}
                                  position={[-0.37, -0.1, 0.27]}
                                >
                                  <T.Mesh
                                    geometry={gltf.nodes['29_DEXTRE012'].geometry}
                                    material={gltf.materials.ISS_03_dull}
                                    position={[-0.3, -0.11, 0.14]}
                                  >
                                    <T.Mesh
                                      geometry={gltf.nodes['29_DEXTRE013'].geometry}
                                      material={gltf.materials.ISS_03_dull}
                                      position={[-1.09, 0.01, 0.06]}
                                    >
                                      <T.Mesh
                                        geometry={gltf.nodes['29_DEXTRE014'].geometry}
                                        material={gltf.materials.ISS_03_dull}
                                        position={[-1.09, -0.01, -0.33]}
                                      >
                                        <T.Mesh
                                          geometry={gltf.nodes['29_DEXTRE015'].geometry}
                                          material={gltf.materials.ISS_03_dull}
                                          position={[-0.28, -0.12, -0.11]}
                                        />
                                      </T.Mesh>
                                    </T.Mesh>
                                  </T.Mesh>
                                </T.Mesh>
                              </T.Mesh>
                            </T.Mesh>
                          </T.Group>
                        </T.Mesh>
                      </T.Mesh>
                    </T.Mesh>
                  </T.Mesh>
                </T.Mesh>
              </T.Mesh>
            </T.Mesh>
          </T.Mesh>
        </T.Group>
        <T.Group position={[-13.81, 0, 2.44]}>
          <T.Mesh
            geometry={gltf.nodes.s0_ani000_5.geometry}
            material={gltf.materials.ISS_02_dull}
          />
          <T.Mesh
            geometry={gltf.nodes.s0_ani000_6.geometry}
            material={gltf.materials.ISS_01_dull}
          />
          <T.Mesh
            geometry={gltf.nodes.s0_ani000_7.geometry}
            material={gltf.materials['ISS_02_dark *']}
          />
          <T.Mesh
            geometry={gltf.nodes.s0_ani000_8.geometry}
            material={gltf.materials.ISS_AO_05}
          />
          <T.Mesh
            geometry={gltf.nodes.s0_ani000_9.geometry}
            material={gltf.materials.ISS_04_dull}
          />
          <T.Group position={[-1.44, -0.01, -0.94]}>
            <T.Mesh
              geometry={gltf.nodes.s0_ani000_15.geometry}
              material={gltf.materials.ISS_04_dull}
            />
            <T.Mesh
              geometry={gltf.nodes.s0_ani000_16.geometry}
              material={gltf.materials.ISS_AO_05}
            />
            <T.Mesh
              geometry={gltf.nodes.s0_ani000_17.geometry}
              material={gltf.materials.ISS_01_dull}
            />
            <T.Mesh
              geometry={gltf.nodes.s0_ani000_18.geometry}
              material={gltf.materials.ISS_02_dull}
            />
          </T.Group>
          <T.Group position={[-10.05, 0.01, -0.82]}>
            <T.Mesh
              geometry={gltf.nodes.s0_ani000_19.geometry}
              material={gltf.materials.ISS_01_dull}
            />
            <T.Mesh
              geometry={gltf.nodes.s0_ani000_20.geometry}
              material={gltf.materials.ISS_04_dull}
            />
            <T.Mesh
              geometry={gltf.nodes.s0_ani000_21.geometry}
              material={gltf.materials.ISS_AO_05}
            />
            <T.Group
              position={[-3.02, -0.03, -0.01]}
              rotation={[Math.PI / 3, 0, 0]}
            >
              <T.Mesh
                geometry={gltf.nodes.p6_ani000.geometry}
                material={gltf.materials.ISS_AO_05}
              />
              <T.Mesh
                geometry={gltf.nodes.p6_ani000_1.geometry}
                material={gltf.materials.ISS_02_dull}
              />
              <T.Mesh
                geometry={gltf.nodes.p6_ani000_2.geometry}
                material={gltf.materials.ISS_AO_03}
              />
              <T.Mesh
                geometry={gltf.nodes.p6_ani000_3.geometry}
                material={gltf.materials['ISS_02_dark *']}
              />
              <T.Mesh
                geometry={gltf.nodes.p6_ani000_4.geometry}
                material={gltf.materials.ISS_01_dull}
              />
              <T.Group position={[-8.14, -0.01, 1.23]}>
                <T.Mesh
                  geometry={gltf.nodes.Cube008_46.geometry}
                  material={gltf.materials.ISS_01_dull}
                />
                <T.Mesh
                  geometry={gltf.nodes.Cube008_47.geometry}
                  material={gltf.materials.ISS_AO_06}
                />
                <T.Mesh
                  geometry={gltf.nodes.Cube008_48.geometry}
                  material={gltf.materials.ISS_02_dull}
                />
                <T.Mesh
                  geometry={gltf.nodes.Cube008_49.geometry}
                  material={gltf.materials['ISS_02_dark *']}
                />
                <T.Group position={[0.49, 0.68, 0.67]}>
                  <T.Mesh
                    geometry={gltf.nodes.p6_ani000_10.geometry}
                    material={gltf.materials.ISS_02_dull}
                  />
                  <T.Mesh
                    geometry={gltf.nodes.p6_ani000_11.geometry}
                    material={gltf.materials.shiny_panel}
                  />
                  <T.Mesh
                    geometry={gltf.nodes.p6_ani000_12.geometry}
                    material={gltf.materials['ISS_02_dark *']}
                  />
                </T.Group>
                <T.Group position={[0.49, -0.68, -2.39]}>
                  <T.Mesh
                    geometry={gltf.nodes.p6_ani000_13.geometry}
                    material={gltf.materials.ISS_02_dull}
                  />
                  <T.Mesh
                    geometry={gltf.nodes.p6_ani000_14.geometry}
                    material={gltf.materials.shiny_panel}
                  />
                  <T.Mesh
                    geometry={gltf.nodes.p6_ani000_15.geometry}
                    material={gltf.materials['ISS_02_dark *']}
                  />
                </T.Group>
                <T.Group position={[-1.44, 0, -0.85]}>
                  <T.Mesh
                    geometry={gltf.nodes.p6_ani000_16.geometry}
                    material={gltf.materials.ISS_02_dull}
                  />
                  <T.Mesh
                    geometry={gltf.nodes.p6_ani000_17.geometry}
                    material={gltf.materials.ISS_AO_03}
                  />
                  <T.Mesh
                    geometry={gltf.nodes.p6_ani000_18.geometry}
                    material={gltf.materials.ISS_01_dull}
                  />
                  <T.Mesh
                    geometry={gltf.nodes.p6_ani000_19.geometry}
                    material={gltf.materials['ISS_02_dark *']}
                  />
                  <T.Group position={[-13.49, 0.68, 1.52]}>
                    <T.Mesh
                      geometry={gltf.nodes.p6_ani000_30.geometry}
                      material={gltf.materials.ISS_02_dull}
                    />
                    <T.Mesh
                      geometry={gltf.nodes.p6_ani000_31.geometry}
                      material={gltf.materials.shiny_panel}
                    />
                    <T.Mesh
                      geometry={gltf.nodes.p6_ani000_32.geometry}
                      material={gltf.materials['ISS_02_dark *']}
                    />
                  </T.Group>
                  <T.Group position={[-13.49, -0.68, -1.53]}>
                    <T.Mesh
                      geometry={gltf.nodes.p6_ani000_33.geometry}
                      material={gltf.materials.ISS_02_dull}
                    />
                    <T.Mesh
                      geometry={gltf.nodes.p6_ani000_34.geometry}
                      material={gltf.materials.shiny_panel}
                    />
                    <T.Mesh
                      geometry={gltf.nodes.p6_ani000_35.geometry}
                      material={gltf.materials['ISS_02_dark *']}
                    />
                  </T.Group>
                </T.Group>
              </T.Group>
            </T.Group>
            <T.Group position={[-1.31, -2.25, 0]}>
              <T.Mesh
                geometry={gltf.nodes.ESP3000.geometry}
                material={gltf.materials.ISS_01_dull}
              />
              <T.Mesh
                geometry={gltf.nodes.ESP3000_1.geometry}
                material={gltf.materials.ISS_01_shiny_n}
              />
              <T.Mesh
                geometry={gltf.nodes.ESP3000_2.geometry}
                material={gltf.materials.ISS_AO_07}
              />
              <T.Mesh
                geometry={gltf.nodes.ESP3000_3.geometry}
                material={gltf.materials.ISS_03_dull}
              />
              <T.Mesh
                geometry={gltf.nodes.ESP3000_4.geometry}
                material={gltf.materials.ISS_04_dull}
              />
            </T.Group>
            <T.Group position={[-1.84, 5.06, 0]}>
              <T.Mesh
                geometry={gltf.nodes.esp2_lo000_4.geometry}
                material={gltf.materials.ISS_AO_07}
              />
              <T.Mesh
                geometry={gltf.nodes.esp2_lo000_5.geometry}
                material={gltf.materials.ISS_04_dull}
              />
              <T.Mesh
                geometry={gltf.nodes.esp2_lo000_6.geometry}
                material={gltf.materials.ISS_01_dull}
              />
              <T.Mesh
                geometry={gltf.nodes.esp2_lo000_7.geometry}
                material={gltf.materials.ISS_03_dull}
              />
            </T.Group>
            <T.Group position={[2.21, -5.07, 0]}>
              <T.Mesh
                geometry={gltf.nodes.esp2_lo000_8.geometry}
                material={gltf.materials.ISS_04_dull}
              />
              <T.Mesh
                geometry={gltf.nodes.esp2_lo000_9.geometry}
                material={gltf.materials.ISS_01_dull}
              />
              <T.Mesh
                geometry={gltf.nodes.esp2_lo000_10.geometry}
                material={gltf.materials.ISS_AO_07}
              />
            </T.Group>
            <T.Group position={[2.11, 3.72, -0.24]}>
              <T.Mesh
                geometry={gltf.nodes.AMS2000.geometry}
                material={gltf.materials.ISS_04_dull}
              />
              <T.Mesh
                geometry={gltf.nodes.AMS2000_1.geometry}
                material={gltf.materials.ISS_AO_07}
              />
              <T.Mesh
                geometry={gltf.nodes.AMS2000_2.geometry}
                material={gltf.materials.ISS_01_dull}
              />
            </T.Group>
          </T.Group>
          <T.Group position={[2.68, 1.91, 0.13]}>
            <T.Mesh
              geometry={gltf.nodes.Cylinder022_63.geometry}
              material={gltf.materials.ISS_03_dull}
            />
            <T.Mesh
              geometry={gltf.nodes.Cylinder022_64.geometry}
              material={gltf.materials.ISS_AO_07}
            />
            <T.Mesh
              geometry={gltf.nodes.Cylinder022_65.geometry}
              material={gltf.materials.ISS_01_dull}
            />
          </T.Group>
        </T.Group>
        <T.Group position={[6.82, 2.24, 1.5]}>
          <T.Mesh
            geometry={gltf.nodes.s0_ani000_10.geometry}
            material={gltf.materials.ISS_02_dull}
          />
          <T.Mesh
            geometry={gltf.nodes.s0_ani000_11.geometry}
            material={gltf.materials.ISS_01_dull}
          />
          <T.Mesh
            geometry={gltf.nodes.s0_ani000_12.geometry}
            material={gltf.materials['ISS_02_dark *']}
          />
          <T.Mesh
            geometry={gltf.nodes.s0_ani000_13.geometry}
            material={gltf.materials.ISS_AO_05}
          />
          <T.Mesh
            geometry={gltf.nodes.s0_ani000_14.geometry}
            material={gltf.materials.ISS_04_dull}
          />
          <T.Group position={[8.43, -2.23, -0.01]}>
            <T.Mesh
              geometry={gltf.nodes.s0_ani000_22.geometry}
              material={gltf.materials.ISS_04_dull}
            />
            <T.Mesh
              geometry={gltf.nodes.s0_ani000_23.geometry}
              material={gltf.materials.ISS_AO_05}
            />
            <T.Mesh
              geometry={gltf.nodes.s0_ani000_24.geometry}
              material={gltf.materials.ISS_01_dull}
            />
            <T.Mesh
              geometry={gltf.nodes.s0_ani000_25.geometry}
              material={gltf.materials.ISS_02_dull}
            />
          </T.Group>
          <T.Group position={[17.04, -2.23, 0.11]}>
            <T.Mesh
              geometry={gltf.nodes.s0_ani000_26.geometry}
              material={gltf.materials.ISS_01_dull}
            />
            <T.Mesh
              geometry={gltf.nodes.s0_ani000_27.geometry}
              material={gltf.materials.ISS_04_dull}
            />
            <T.Mesh
              geometry={gltf.nodes.s0_ani000_28.geometry}
              material={gltf.materials.ISS_AO_05}
            />
            <T.Group
              position={[3.02, 0.01, -0.03]}
              rotation={[Math.PI / 3, 0, 0]}
            >
              <T.Mesh
                geometry={gltf.nodes.p6_ani000_5.geometry}
                material={gltf.materials.ISS_AO_05}
              />
              <T.Mesh
                geometry={gltf.nodes.p6_ani000_6.geometry}
                material={gltf.materials.ISS_02_dull}
              />
              <T.Mesh
                geometry={gltf.nodes.p6_ani000_7.geometry}
                material={gltf.materials.ISS_AO_03}
              />
              <T.Mesh
                geometry={gltf.nodes.p6_ani000_8.geometry}
                material={gltf.materials['ISS_02_dark *']}
              />
              <T.Mesh
                geometry={gltf.nodes.p6_ani000_9.geometry}
                material={gltf.materials.ISS_01_dull}
              />
              <T.Group position={[8.14, -0.01, -1.23]}>
                <T.Mesh
                  geometry={gltf.nodes.Cube008_50.geometry}
                  material={gltf.materials.ISS_01_dull}
                />
                <T.Mesh
                  geometry={gltf.nodes.Cube008_51.geometry}
                  material={gltf.materials.ISS_AO_06}
                />
                <T.Mesh
                  geometry={gltf.nodes.Cube008_52.geometry}
                  material={gltf.materials.ISS_02_dull}
                />
                <T.Mesh
                  geometry={gltf.nodes.Cube008_53.geometry}
                  material={gltf.materials['ISS_02_dark *']}
                />
                <T.Group position={[1.44, 0, 0.85]}>
                  <T.Mesh
                    geometry={gltf.nodes.p6_ani000_20.geometry}
                    material={gltf.materials.ISS_02_dull}
                  />
                  <T.Mesh
                    geometry={gltf.nodes.p6_ani000_21.geometry}
                    material={gltf.materials.ISS_AO_03}
                  />
                  <T.Mesh
                    geometry={gltf.nodes.p6_ani000_22.geometry}
                    material={gltf.materials.ISS_01_dull}
                  />
                  <T.Mesh
                    geometry={gltf.nodes.p6_ani000_23.geometry}
                    material={gltf.materials['ISS_02_dark *']}
                  />
                  <T.Group position={[13.49, -0.68, 1.53]}>
                    <T.Mesh
                      geometry={gltf.nodes.p6_ani000_36.geometry}
                      material={gltf.materials.ISS_02_dull}
                    />
                    <T.Mesh
                      geometry={gltf.nodes.p6_ani000_37.geometry}
                      material={gltf.materials.shiny_panel}
                    />
                    <T.Mesh
                      geometry={gltf.nodes.p6_ani000_38.geometry}
                      material={gltf.materials['ISS_02_dark *']}
                    />
                  </T.Group>
                  <T.Group position={[13.49, 0.68, -1.52]}>
                    <T.Mesh
                      geometry={gltf.nodes.p6_ani000_39.geometry}
                      material={gltf.materials.ISS_02_dull}
                    />
                    <T.Mesh
                      geometry={gltf.nodes.p6_ani000_40.geometry}
                      material={gltf.materials.shiny_panel}
                    />
                    <T.Mesh
                      geometry={gltf.nodes.p6_ani000_41.geometry}
                      material={gltf.materials['ISS_02_dark *']}
                    />
                  </T.Group>
                </T.Group>
                <T.Group position={[-0.49, -0.68, 2.39]}>
                  <T.Mesh
                    geometry={gltf.nodes.p6_ani000_24.geometry}
                    material={gltf.materials.ISS_02_dull}
                  />
                  <T.Mesh
                    geometry={gltf.nodes.p6_ani000_25.geometry}
                    material={gltf.materials.shiny_panel}
                  />
                  <T.Mesh
                    geometry={gltf.nodes.p6_ani000_26.geometry}
                    material={gltf.materials['ISS_02_dark *']}
                  />
                </T.Group>
                <T.Group position={[-0.49, 0.68, -0.67]}>
                  <T.Mesh
                    geometry={gltf.nodes.p6_ani000_27.geometry}
                    material={gltf.materials.ISS_02_dull}
                  />
                  <T.Mesh
                    geometry={gltf.nodes.p6_ani000_28.geometry}
                    material={gltf.materials.shiny_panel}
                  />
                  <T.Mesh
                    geometry={gltf.nodes.p6_ani000_29.geometry}
                    material={gltf.materials['ISS_02_dark *']}
                  />
                </T.Group>
              </T.Group>
            </T.Group>
            <T.Group position={[1.06, -5.07, -0.04]}>
              <T.Mesh
                geometry={gltf.nodes.esp2_lo000_11.geometry}
                material={gltf.materials.ISS_AO_07}
              />
              <T.Mesh
                geometry={gltf.nodes.esp2_lo000_12.geometry}
                material={gltf.materials.ISS_03_dull}
              />
              <T.Mesh
                geometry={gltf.nodes.esp2_lo000_13.geometry}
                material={gltf.materials.ISS_04_dull}
              />
              <T.Mesh
                geometry={gltf.nodes.esp2_lo000_14.geometry}
                material={gltf.materials.ISS_01_dull}
              />
            </T.Group>
            <T.Group position={[1.84, 5.06, -0.07]}>
              <T.Mesh
                geometry={gltf.nodes.esp2_lo000_15.geometry}
                material={gltf.materials.ISS_AO_08}
              />
              <T.Mesh
                geometry={gltf.nodes.esp2_lo000_16.geometry}
                material={gltf.materials.ISS_01_dull}
              />
              <T.Mesh
                geometry={gltf.nodes.esp2_lo000_17.geometry}
                material={gltf.materials.ISS_04_dull}
              />
              <T.Mesh
                geometry={gltf.nodes.esp2_lo000_18.geometry}
                material={gltf.materials.ISS_03_dull}
              />
            </T.Group>
          </T.Group>
        </T.Group>
      </T.Group>
      <T.Group position={[0, 0, 9.16]}>
        <T.Mesh
          geometry={gltf.nodes.Cylinder022_36.geometry}
          material={gltf.nodes.Cylinder022_36.material}
        />
        <T.Mesh
          geometry={gltf.nodes.Cylinder022_37.geometry}
          material={gltf.materials.ISS_01_shiny_n}
        />
        <T.Mesh
          geometry={gltf.nodes.Cylinder022_38.geometry}
          material={gltf.materials.ISS_AO_01}
        />
        <T.Mesh
          geometry={gltf.nodes.Cylinder022_39.geometry}
          material={gltf.materials.ISS_01_dull}
        />
        <T.Group position={[0, 0, 6.97]}>
          <T.Mesh
            geometry={gltf.nodes.Cylinder022_46.geometry}
            material={gltf.materials.ISS_01_dull}
          />
          <T.Mesh
            geometry={gltf.nodes.Cylinder022_47.geometry}
            material={gltf.materials.ISS_AO_02}
          />
          <T.Mesh
            geometry={gltf.nodes.Cylinder022_48.geometry}
            material={gltf.materials.ISS_AO_01}
          />
        </T.Group>
        <T.Group position={[-4.17, 0, 4.83]}>
          <T.Mesh
            geometry={gltf.nodes.Cylinder022_49.geometry}
            material={gltf.nodes.Cylinder022_49.material}
          />
          <T.Mesh
            geometry={gltf.nodes.Cylinder022_50.geometry}
            material={gltf.materials.ISS_02_dull}
          />
          <T.Mesh
            geometry={gltf.nodes.Cylinder022_51.geometry}
            material={gltf.materials.ISS_01_dull}
          />
          <T.Mesh
            geometry={gltf.nodes.Cylinder022_52.geometry}
            material={gltf.materials.ISS_01_shiny_n}
          />
          <T.Mesh
            geometry={gltf.nodes.Cylinder022_53.geometry}
            material={gltf.materials.ISS_AO_01}
          />
          <T.Mesh
            geometry={gltf.nodes.Cylinder022_54.geometry}
            material={gltf.materials.ISS_AO_06}
          />
          <T.Group position={[-5.9, -1.33, 0]}>
            <T.Mesh
              geometry={gltf.nodes.Cube008_35.geometry}
              material={gltf.materials.ISS_04_dull}
            />
            <T.Mesh
              geometry={gltf.nodes.Cube008_36.geometry}
              material={gltf.materials.ISS_AO_07}
            />
            <T.Mesh
              geometry={gltf.nodes.Cube008_37.geometry}
              material={gltf.materials.ISS_03_dull}
            />
            <T.Mesh
              geometry={gltf.nodes.Cube008_38.geometry}
              material={gltf.materials.foil_silver}
            />
            <T.Mesh
              geometry={gltf.nodes.RapidScat_dish.geometry}
              material={gltf.materials.ISS_04_dull}
              position={[-0.73, -0.83, -0.22]}
            />
          </T.Group>
        </T.Group>
        <T.Group position={[7.48, 0, 4.83]}>
          <T.Mesh
            geometry={gltf.nodes.Cylinder022_55.geometry}
            material={gltf.nodes.Cylinder022_55.material}
          />
          <T.Mesh
            geometry={gltf.nodes.Cylinder022_56.geometry}
            material={gltf.materials.ISS_03_dull}
          />
          <T.Mesh
            geometry={gltf.nodes.Cylinder022_57.geometry}
            material={gltf.materials.ISS_01_dull}
          />
          <T.Mesh
            geometry={gltf.nodes.Cylinder022_58.geometry}
            material={gltf.materials.ISS_AO_01}
          />
          <T.Mesh
            geometry={gltf.nodes.Cylinder022_59.geometry}
            material={gltf.materials.ISS_03_shiny_n}
          />
          <T.Mesh
            geometry={gltf.nodes.Cylinder022_60.geometry}
            material={gltf.materials.ISS_AO_04}
          />
          <T.Group position={[2.82, 4.04, 0]}>
            <T.Mesh
              geometry={gltf.nodes.Cylinder022_66.geometry}
              material={gltf.nodes.Cylinder022_66.material}
            />
            <T.Mesh
              geometry={gltf.nodes.Cylinder022_67.geometry}
              material={gltf.materials.ISS_01_dull}
            />
            <T.Mesh
              geometry={gltf.nodes.Cylinder022_68.geometry}
              material={gltf.materials.ISS_03_shiny_n}
            />
            <T.Mesh
              geometry={gltf.nodes.Cylinder022_69.geometry}
              material={gltf.materials.ISS_AO_01}
            />
            <T.Mesh
              geometry={gltf.nodes.Cylinder022_70.geometry}
              material={gltf.materials.ISS_AO_04}
            />
            <T.Mesh
              geometry={gltf.nodes.Cylinder022_71.geometry}
              material={gltf.materials.ISS_03_dull}
            />
          </T.Group>
          <T.Mesh
            geometry={gltf.nodes['31_Robotic_Arm'].geometry}
            material={gltf.materials.ISS_04_dull}
            position={[5.14, 0.88, 1.68]}
          >
            <T.Mesh
              geometry={gltf.nodes['31_Robotic_Arm001'].geometry}
              material={gltf.materials.ISS_04_dull}
              position={[0.76, 0.3, -0.33]}
            >
              <T.Mesh
                geometry={gltf.nodes['31_Robotic_Arm002'].geometry}
                material={gltf.materials.ISS_04_dull}
                position={[0, 0.41, 0.53]}
              >
                <T.Mesh
                  geometry={gltf.nodes['31_Robotic_Arm003'].geometry}
                  material={gltf.materials.ISS_04_dull}
                  position={[4.07, 0, -0.54]}
                >
                  <T.Mesh
                    geometry={gltf.nodes['31_Robotic_Arm004'].geometry}
                    material={gltf.materials.ISS_04_dull}
                    position={[4.07, 0, -0.52]}
                  >
                    <T.Mesh
                      geometry={gltf.nodes['31_Robotic_Arm005'].geometry}
                      material={gltf.materials.ISS_04_dull}
                      position={[0.44, 0.52, 0.01]}
                    />
                  </T.Mesh>
                </T.Mesh>
              </T.Mesh>
            </T.Mesh>
          </T.Mesh>
          <T.Group position={[6.05, -1.56, -0.09]}>
            <T.Mesh
              geometry={gltf.nodes.Cube008_39.geometry}
              material={gltf.materials.ISS_03_dull}
            />
            <T.Mesh
              geometry={gltf.nodes.Cube008_40.geometry}
              material={gltf.materials.ISS_04_dull}
            />
            <T.Mesh
              geometry={gltf.nodes.Cube008_41.geometry}
              material={gltf.materials.ISS_AO_07}
            />
            <T.Mesh
              geometry={gltf.nodes.Cube008_42.geometry}
              material={gltf.materials.ISS_01_dull}
            />
          </T.Group>
          <T.Group position={[10.49, -1.95, -1.08]}>
            <T.Mesh
              geometry={gltf.nodes.Cube008_43.geometry}
              material={gltf.materials.ISS_03_dull}
            />
            <T.Mesh
              geometry={gltf.nodes.Cube008_44.geometry}
              material={gltf.materials.ISS_01_dull}
            />
          </T.Group>
        </T.Group>
      </T.Group>
      <T.Mesh
        geometry={gltf.nodes.Destiny_Window_Cover.geometry}
        material={gltf.materials.ISS_01_dull}
        position={[0, -2.32, 4.78]}
      />
    </T.Group>
    <T.Group position={[-3.69, -0.37, 0]}>
      <T.Mesh
        geometry={gltf.nodes.Cylinder022_20.geometry}
        material={gltf.nodes.Cylinder022_20.material}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder022_21.geometry}
        material={gltf.materials.ISS_03_dull}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder022_22.geometry}
        material={gltf.materials.ISS_AO_04}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder022_23.geometry}
        material={gltf.materials.ISS_01_dull}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder022_24.geometry}
        material={gltf.materials.ISS_03_shiny_n}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder022_25.geometry}
        material={gltf.materials.ISS_01_shiny_n}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder022_26.geometry}
        material={gltf.materials.ISS_AO_01}
      />
      <T.Group position={[0.64, 0, 2.43]}>
        <T.Mesh
          geometry={gltf.nodes.esp2_lo000.geometry}
          material={gltf.materials.ISS_04_dull}
        />
        <T.Mesh
          geometry={gltf.nodes.esp2_lo000_1.geometry}
          material={gltf.materials.ISS_01_dull}
        />
        <T.Mesh
          geometry={gltf.nodes.esp2_lo000_2.geometry}
          material={gltf.materials.ISS_01_shiny_n}
        />
        <T.Mesh
          geometry={gltf.nodes.esp2_lo000_3.geometry}
          material={gltf.materials.ISS_AO_07}
        />
      </T.Group>
    </T.Group>
    <T.Group position={[2.23, 0, 0]}>
      <T.Mesh
        geometry={gltf.nodes.Cylinder022_27.geometry}
        material={gltf.nodes.Cylinder022_27.material}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder022_28.geometry}
        material={gltf.materials.ISS_01_shiny_n}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder022_29.geometry}
        material={gltf.materials.ISS_AO_01}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder022_30.geometry}
        material={gltf.materials.ISS_01_dull}
      />
      <T.Group position={[6.97, 0, 0]}>
        <T.Mesh
          geometry={gltf.nodes.Cylinder022_40.geometry}
          material={gltf.materials.ISS_01_dull}
        />
        <T.Mesh
          geometry={gltf.nodes.Cylinder022_41.geometry}
          material={gltf.materials.ISS_AO_02}
        />
        <T.Mesh
          geometry={gltf.nodes.Cylinder022_42.geometry}
          material={gltf.materials.ISS_AO_01}
        />
      </T.Group>
      <T.Group position={[4.83, -2.62, 0]}>
        <T.Mesh
          geometry={gltf.nodes.Cylinder022_43.geometry}
          material={gltf.materials.ISS_04_dull}
        />
        <T.Mesh
          geometry={gltf.nodes.Cylinder022_44.geometry}
          material={gltf.materials.ISS_01_dull}
        />
        <T.Mesh
          geometry={gltf.nodes.Cylinder022_45.geometry}
          material={gltf.materials.ISS_AO_01}
        />
        <T.Mesh
          geometry={gltf.nodes['38_Cupola001'].geometry}
          material={gltf.materials.ISS_04_dull}
          position={[1.2, -0.36, -0.01]}
        />
        <T.Mesh
          geometry={gltf.nodes['38_Cupola002'].geometry}
          material={gltf.materials.ISS_04_dull}
          position={[0.58, -0.36, 1.05]}
        />
        <T.Mesh
          geometry={gltf.nodes['38_Cupola003'].geometry}
          material={gltf.materials.ISS_04_dull}
          position={[-0.57, -0.36, 1.05]}
        />
        <T.Mesh
          geometry={gltf.nodes['38_Cupola004'].geometry}
          material={gltf.materials.ISS_04_dull}
          position={[-1.2, -0.36, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['38_Cupola005'].geometry}
          material={gltf.materials.ISS_04_dull}
          position={[-0.58, -0.36, -1.05]}
        />
        <T.Mesh
          geometry={gltf.nodes['38_Cupola006'].geometry}
          material={gltf.materials.ISS_04_dull}
          position={[0.62, -0.36, -1.03]}
        />
        <T.Mesh
          geometry={gltf.nodes['38_Cupola007'].geometry}
          material={gltf.materials.ISS_04_dull}
          position={[-0.62, -1.05, 0.3]}
        />
        <T.Mesh
          geometry={gltf.nodes.ISS.geometry}
          material={gltf.nodes.ISS.material}
          position={[0, -0.02, 0]}
        />
      </T.Group>
    </T.Group>
    <T.Group position={[0, -2.19, 0]}>
      <T.Mesh
        geometry={gltf.nodes.Cylinder022_31.geometry}
        material={gltf.nodes.Cylinder022_31.material}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder022_32.geometry}
        material={gltf.materials.ISS_01_dull}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder022_33.geometry}
        material={gltf.materials.ISS_01_shiny_n}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder022_34.geometry}
        material={gltf.materials.ISS_AO_01}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder022_35.geometry}
        material={gltf.materials.ISS_AO_06}
      />
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
