<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.3 --types --transform moon.glb
Author: RenderX (https://sketchfab.com/RenderX)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/moon-26cc0b7878bb4d919b68e2be399db466
Title: moon
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import type { Snippet } from 'svelte'
  import { T, type Props } from '@threlte/core'
  import { useGltf, useGltfAnimations, useDraco } from '@threlte/extras'

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group
    children?: Snippet<[{ ref: THREE.Group }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  ref = new Group()

  type ActionName = 'Sphere|SphereAction'
  type GLTFResult = {
    nodes: {
      Sphere_Material001_0: THREE.Mesh
    }
    materials: {
      ['Material.001']: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/moon-transformed.glb', { dracoLoader: useDraco() })

  export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref)
</script>

<T
  is={ref}
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group name="Sketchfab_Scene">
      <T.Group
        name="RootNode"
        scale={0.01}
      >
        <T.Group
          name="Sphere"
          rotation={[-1.26, 0.49, 0.96]}
          scale={100}
        >
          <T.Mesh
            name="Sphere_Material001_0"
            geometry={gltf.nodes.Sphere_Material001_0.geometry}
            material={gltf.materials['Material.001']}
          />
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T>
